// Rich mock data used as the instant default on every page.
// Real API responses replace these when the backend is reachable.

export const MOCK_PERSONAS = [
  {
    id: '1',
    user_id: 'demo-user',
    name: 'Emeka O.',
    age_range: '25-34',
    city: 'Lagos',
    lga: 'Eti-Osa',
    primary_language: 'igbo',
    review_style: 'expressive',
    avg_rating: 4.2,
    sentiment_volatility: 'medium',
    categories_reviewed: ['tech_gadget', 'fintech', 'restaurant'],
    sample_reviews: [
      'The speed dey sharp sharp, but price high like NEPA restoring light.',
      'Everything set finish, clean design wey no go fall hand.',
    ],
    cultural_markers: ['sharp sharp', 'NEPA', 'fall hand'],
    pidgin_intensity: 0.82,
    voice_radar: { skepticism: 0.72, aspiration: 0.88, value: 0.76, sass: 0.68, loyalty: 0.64 },
    cultural_density: 88,
    status: 'active_oracle',
  },
  {
    id: '2',
    user_id: 'demo-user',
    name: 'Aisha H.',
    age_range: '25-34',
    city: 'Kano',
    lga: 'Tarauni',
    primary_language: 'hausa',
    review_style: 'analytical',
    avg_rating: 4.5,
    sentiment_volatility: 'low',
    categories_reviewed: ['fashion', 'beauty', 'food'],
    sample_reviews: ['Quality dey, but delivery timing needs discipline.'],
    cultural_markers: ['quality dey', 'timing'],
    pidgin_intensity: 0.55,
    voice_radar: { skepticism: 0.58, aspiration: 0.74, value: 0.82, sass: 0.42, loyalty: 0.79 },
    cultural_density: 86,
    status: 'active',
  },
  {
    id: '3',
    user_id: 'demo-user',
    name: 'Tunde B.',
    age_range: '18-24',
    city: 'Lagos',
    lga: 'Yaba',
    primary_language: 'yoruba',
    review_style: 'casual',
    avg_rating: 3.9,
    sentiment_volatility: 'high',
    categories_reviewed: ['tech_gadget', 'entertainment', 'fintech'],
    sample_reviews: ['App clean, but the onboarding stress no make sense.'],
    cultural_markers: ['no make sense', 'clean'],
    pidgin_intensity: 0.75,
    voice_radar: { skepticism: 0.8, aspiration: 0.66, value: 0.7, sass: 0.73, loyalty: 0.52 },
    cultural_density: 75,
    status: 'active',
  },
  {
    id: '4',
    user_id: 'demo-user',
    name: 'Ngozi A.',
    age_range: '35-44',
    city: 'Enugu',
    lga: 'Enugu East',
    primary_language: 'igbo',
    review_style: 'analytical',
    avg_rating: 4.3,
    sentiment_volatility: 'low',
    categories_reviewed: ['food', 'fashion', 'beauty'],
    sample_reviews: ['The quality speaks for itself. I tested three alternatives — this one maintains standard.'],
    cultural_markers: ['maintain standard', 'i no dey play'],
    pidgin_intensity: 0.35,
    voice_radar: { skepticism: 0.8, aspiration: 0.6, value: 0.9, sass: 0.3, loyalty: 0.85 },
    cultural_density: 62,
    status: 'active',
  },
  {
    id: '5',
    user_id: 'demo-user',
    name: 'Biodun F.',
    age_range: '25-34',
    city: 'Ibadan',
    lga: 'Ibadan North',
    primary_language: 'yoruba',
    review_style: 'street_honest',
    avg_rating: 3.6,
    sentiment_volatility: 'medium',
    categories_reviewed: ['restaurant', 'food', 'entertainment'],
    sample_reviews: ['E no reach the hype dem give am. The jollof dey okay but nothing to write home about.'],
    cultural_markers: ['nothing to write home about', 'the hype'],
    pidgin_intensity: 0.68,
    voice_radar: { skepticism: 0.85, aspiration: 0.5, value: 0.88, sass: 0.7, loyalty: 0.45 },
    cultural_density: 79,
    status: 'active',
  },
  {
    id: '6',
    user_id: 'demo-user',
    name: 'Musa D.',
    age_range: '35-44',
    city: 'Abuja',
    lga: 'Garki',
    primary_language: 'hausa',
    review_style: 'aspirational',
    avg_rating: 4.6,
    sentiment_volatility: 'low',
    categories_reviewed: ['tech_gadget', 'fintech', 'fashion'],
    sample_reviews: ['This is exactly what Abuja professionals need. Modern, efficient, worth the investment.'],
    cultural_markers: ['worth the investment', 'Abuja professionals'],
    pidgin_intensity: 0.28,
    voice_radar: { skepticism: 0.45, aspiration: 0.92, value: 0.78, sass: 0.25, loyalty: 0.88 },
    cultural_density: 55,
    status: 'active',
  },
  {
    id: '7',
    user_id: 'demo-user',
    name: 'Chisom E.',
    age_range: '18-24',
    city: 'Port Harcourt',
    lga: 'Port Harcourt City',
    primary_language: 'igbo',
    review_style: 'expressive',
    avg_rating: 4.1,
    sentiment_volatility: 'high',
    categories_reviewed: ['beauty', 'fashion', 'entertainment'],
    sample_reviews: ['Biko, this product na fire o! PH girls no dey play with their skin, and this one dey deliver.'],
    cultural_markers: ['biko', 'na fire', 'PH girls'],
    pidgin_intensity: 0.79,
    voice_radar: { skepticism: 0.55, aspiration: 0.82, value: 0.72, sass: 0.78, loyalty: 0.65 },
    cultural_density: 83,
    status: 'active',
  },
  {
    id: '8',
    user_id: 'demo-user',
    name: 'Fatima I.',
    age_range: '45-54',
    city: 'Kano',
    lga: 'Fagge',
    primary_language: 'hausa',
    review_style: 'expressive',
    avg_rating: 4.7,
    sentiment_volatility: 'low',
    categories_reviewed: ['food', 'beauty', 'fashion'],
    sample_reviews: ['Wallahi, this is something else entirely. Quality wey I no expect at this price. Kaico!'],
    cultural_markers: ['wallahi', 'kaico'],
    pidgin_intensity: 0.52,
    voice_radar: { skepticism: 0.6, aspiration: 0.7, value: 0.95, sass: 0.5, loyalty: 0.9 },
    cultural_density: 78,
    status: 'active',
  },
  {
    id: '9',
    user_id: 'demo-user',
    name: 'Seun A.',
    age_range: '25-34',
    city: 'Lagos',
    lga: 'Surulere',
    primary_language: 'yoruba',
    review_style: 'hyper_critical',
    avg_rating: 3.2,
    sentiment_volatility: 'high',
    categories_reviewed: ['tech_gadget', 'fintech', 'restaurant'],
    sample_reviews: ['The app dey behave like PHCN — one moment e dey work, next moment darkness. Sort your infrastructure abeg.'],
    cultural_markers: ['behave like PHCN', 'sort am'],
    pidgin_intensity: 0.83,
    voice_radar: { skepticism: 0.95, aspiration: 0.55, value: 0.85, sass: 0.88, loyalty: 0.35 },
    cultural_density: 85,
    status: 'active',
  },
  {
    id: '10',
    user_id: 'demo-user',
    name: 'Ifeanyi O.',
    age_range: '35-44',
    city: 'Onitsha',
    lga: 'Onitsha North',
    primary_language: 'igbo',
    review_style: 'street_honest',
    avg_rating: 4.0,
    sentiment_volatility: 'medium',
    categories_reviewed: ['food', 'fashion', 'restaurant'],
    sample_reviews: ['Onitsha market no dey lie — if product dey sell here e don pass quality test. This one fit enter.'],
    cultural_markers: ['Onitsha market', 'pass quality test'],
    pidgin_intensity: 0.72,
    voice_radar: { skepticism: 0.78, aspiration: 0.65, value: 0.92, sass: 0.6, loyalty: 0.7 },
    cultural_density: 80,
    status: 'active',
  },
  {
    id: '11',
    user_id: 'demo-user',
    name: 'Zainab M.',
    age_range: '18-24',
    city: 'Abuja',
    lga: 'Wuse',
    primary_language: 'hausa',
    review_style: 'aspirational',
    avg_rating: 4.4,
    sentiment_volatility: 'low',
    categories_reviewed: ['beauty', 'fashion', 'entertainment'],
    sample_reviews: ['This is giving what it should give. Abuja girlies will love — clean, premium, no stress.'],
    cultural_markers: ['Abuja girlies', 'no stress'],
    pidgin_intensity: 0.45,
    voice_radar: { skepticism: 0.4, aspiration: 0.95, value: 0.7, sass: 0.65, loyalty: 0.72 },
    cultural_density: 65,
    status: 'active',
  },
  {
    id: '12',
    user_id: 'demo-user',
    name: 'Dele A.',
    age_range: '45-54',
    city: 'Lagos',
    lga: 'Ikeja',
    primary_language: 'yoruba',
    review_style: 'analytical',
    avg_rating: 4.2,
    sentiment_volatility: 'low',
    categories_reviewed: ['food', 'fintech', 'tech_gadget'],
    sample_reviews: ['Tested this product over three months. Quality consistent, customer service responsive. Recommended.'],
    cultural_markers: ['consistent', 'three months test'],
    pidgin_intensity: 0.22,
    voice_radar: { skepticism: 0.7, aspiration: 0.65, value: 0.9, sass: 0.2, loyalty: 0.88 },
    cultural_density: 52,
    status: 'active',
  },
  {
    id: '13',
    user_id: 'demo-user',
    name: 'Amaka N.',
    age_range: '18-24',
    city: 'Enugu',
    lga: 'Enugu South',
    primary_language: 'igbo',
    review_style: 'expressive',
    avg_rating: 4.8,
    sentiment_volatility: 'high',
    categories_reviewed: ['beauty', 'entertainment', 'fashion'],
    sample_reviews: ['Chai! This don burst my brain o. As Enugu babe I know quality when I see am. 5 stars, no debate!'],
    cultural_markers: ['burst my brain', 'chai', 'no debate'],
    pidgin_intensity: 0.88,
    voice_radar: { skepticism: 0.45, aspiration: 0.9, value: 0.75, sass: 0.85, loyalty: 0.7 },
    cultural_density: 90,
    status: 'active',
  },
  {
    id: '14',
    user_id: 'demo-user',
    name: 'Hassan U.',
    age_range: '25-34',
    city: 'Kano',
    lga: 'Nassarawa',
    primary_language: 'hausa',
    review_style: 'casual',
    avg_rating: 3.8,
    sentiment_volatility: 'medium',
    categories_reviewed: ['food', 'tech_gadget', 'fintech'],
    sample_reviews: ['Does the job. Nothing too extra but nothing to complain about either. Value for money sha.'],
    cultural_markers: ['value for money', 'sha'],
    pidgin_intensity: 0.42,
    voice_radar: { skepticism: 0.62, aspiration: 0.55, value: 0.85, sass: 0.35, loyalty: 0.75 },
    cultural_density: 60,
    status: 'active',
  },
  {
    id: '15',
    user_id: 'demo-user',
    name: 'Sola B.',
    age_range: '45-54',
    city: 'Ibadan',
    lga: 'Ibadan South West',
    primary_language: 'yoruba',
    review_style: 'street_honest',
    avg_rating: 4.5,
    sentiment_volatility: 'low',
    categories_reviewed: ['food', 'restaurant', 'fashion'],
    sample_reviews: ['I don chop for this place before and I go chop again. The banga soup na original — e remind me of my mother kitchen.'],
    cultural_markers: ['I don chop', 'original recipe', 'mother kitchen'],
    pidgin_intensity: 0.76,
    voice_radar: { skepticism: 0.65, aspiration: 0.58, value: 0.88, sass: 0.52, loyalty: 0.92 },
    cultural_density: 77,
    status: 'active',
  },
]

export const MOCK_PERSONA_BY_ID: Record<string, typeof MOCK_PERSONAS[0]> = Object.fromEntries(
  MOCK_PERSONAS.map((p) => [p.id, p])
)

export const MOCK_STATS = {
  total_personas: 15,
  active_personas: 15,
  cities_covered: 12,
  languages_supported: 5,
  avg_cultural_density: 0.87,
}

export const MOCK_EVAL = {
  task_a: { bertscore_f1: 0.87, rouge_l: 0.41, rmse: 0.68, cvi_hit_rate: 0.74, human_eval_score: 4.2 },
  task_b: { ndcg_at_10: 0.89, hit_rate_at_5: 0.82, cold_start_ndcg: 0.76, contextual_relevance_human: 4.3 },
}

export const MOCK_SIMULATE_RESULT = {
  review_text: "E be like say this Zobo fine die o — the colour deep like Lagos twilight and the taste sharp sharp. The packaging dey show class but abeg, the price too high for ordinary market woman. I go manage sha, taste dey there. Four stars from me — if dem reduce price small, e go be five.",
  predicted_rating: 4,
  behavioural_fidelity_score: 0.84,
  voice_profile_used: { pidgin_intensity: 0.82 },
}

export const MOCK_RECOMMENDATIONS = [
  {
    item_id: 'rec_001',
    name: 'Yellow Chilli Restaurant',
    category: 'Nigerian Fine Dining',
    predicted_rating: 4.4,
    context_score: 0.91,
    location: 'Victoria Island, Lagos',
    price_tier: '₦₦₦',
    reasoning: 'Matches your "Owambe DJ" mood with high-energy evening service and live Afrobeats band on Fridays.',
  },
  {
    item_id: 'rec_002',
    name: 'Nok by Alara',
    category: 'African Fusion',
    predicted_rating: 4.9,
    context_score: 0.87,
    location: 'Victoria Island, Lagos',
    price_tier: '₦₦',
    reasoning: 'Creative fusion menu — the oxtail stew and jollof risotto consistently rank highest for celebratory occasions in your budget range.',
  },
  {
    item_id: 'rec_003',
    name: 'Aboki Suya Spot',
    category: 'Street Food',
    predicted_rating: 4.8,
    context_score: 0.83,
    location: 'Palmgrove, Lagos',
    price_tier: '₦',
    reasoning: 'Suya signal from your cold-start answers. Hausa mallam has been grilling on this corner 15 years — cultural authenticity score 94%.',
  },
]
